---
title: Розовое Окно
description: Описание проекта Розовое Окно
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/Portfolio/Cases/Case%20№%201" # Укажите основную базу URL вашего проекта
url: "https://gr-move.github.io"
---