name: Update Tech Stack
on:
  push:
    paths:
      - 'Cases/**/_techstack.md'
    branches: [ main ]

jobs:
  update_techstack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install tabulate mermaid-markdown
        
    - name: Run update script
      run: |
        python update_techstack.py
        cat techstack.md
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Auto-update tech stack'
        file_pattern: techstack.md
